def main_plot_1():
    yield "You've come to the fortress to find the Captain.\n"
    yield "But suddendly you heard two soldiers against a wall and decided to eavesdrop them.\n"
    yield "Officer: How bad is it?\n"
    yield "Soldier: Bad. We've just lost connection with two Forposts at the North.\n"
    yield "Officer: So it wasn't a rumors. King really decided to send every soldier in the kingdom to North Forest.\n"
    yield "You wanted to listen more, but accidently dropped a vase.\n"
    yield "You didn't want to get caught, so you ran away.\n"
    yield "."
    yield ".."
    yield "..."
    yield "You found Captain's office. You knocked 3 times, then the door was opened.\n"
    yield "Captain Mave: Oh, you here, finally. Come inside.\n"
    yield "His office was smaller, than you imagined.\n"
    yield "On the wall were 2 swords in X position. Not any paiting or something rich.\n"
    yield "You: You wanted to see me.\n"
    yield "Mave: Yeah, of course. Take a seat.\n"
    yield "Mave: So, I was going to tell you about something. I wanna see you in guard.\n"
    yield "You: You've got to be kidding me?!\n"
    yield "Mave: No, I'm not, I was watching you for a long time and recent battle prove me you're a good candidate for this.\n"
    yield "You: This is honor for me, Captain.\n"
    yield "Mave: Then we should waste no time, we need to go to Guard Camp, there you will go through special training.\n"
    yield "You: Yes, sir.\n"
    yield "Next day, you went to Guard Camp\n"
    yield "Prologue: Chapter 1 completed"

def main_plot_2():
    from game import main_hero
    yield "Guard Camp.\n\nDecember 23. 12:38"
    yield "Mave: Too slow!\n"
    yield f"Mave: More impact, {main_hero.name}\n"
    yield "You were training around 10 days to be strong enough to be in Captain Mave's Special guard\n"
    yield "Today was you're examination you passed with hard efforts, so from today you're one of the 30 members of Special Guard\n"
    yield f"Mave: Meet me in the Site later, {main_hero.name}"
    yield "Mave: And my congratulations, son\n"