def main_plot_1():
    yield "You've come to the fortress to find the Captain.\n"
    yield "But suddendly you heard two soldiers against a wall and decided to eavesdrop them.\n"
    yield "Officer: How bad is it?\n"
    yield "Soldier: Bad. We've just lost connection with two Forposts at the North.\n"
    yield "Officer: So it wasn't a rumors. King really decided to send every soldier in the kingdom to North Forest.\n"
    yield "You wanted to listen more, but accidently dropped a vase.\n"
    yield "You didn't want to get caught, so you ran away.\n"
    yield "."
    yield ".."
    yield "..."
    yield "You found Captain's office. You knocked 3 times, then the door was opened.\n"
    yield "Captain Mave: Oh, you here, finally. Come inside.\n"
    yield "His office was smaller, than you imagined.\n"
    yield "On the wall were 2 swords in X position. Not any paiting or something rich.\n"
    yield "You: You wanted to see me.\n"
    yield "Mave: Yeah, of course. Take a seat.\n"
    yield "Mave: So, I was going to tell you about something. I wanna see you in guard.\n"
    yield "You: You've got to be kidding me?!"
    yield "Mave: No, I'm not, I was watching you for a long time and recent battle prove me you're a good candidate for this.\n"
    yield "You: This is honor for me, Captain.\n"
    yield "Mave: Good, because I..."
    yield "Officer: Captain, can you talk with me for a minute. That is neccesary.\n"
    yield "Mave: Okay, if it's neccesary. Can you stay in a room for a while, I need to talk with officer Shaw.\n"
    yield "You: Of course, no problem.\n"
    yield "They left you alone in a room for an hour. Then he came back and told you: We need to go tommorow. In North Forest"
    yield "You: What happened?.\n"
    yield "Mave: A war.\n"
    yield "You decided to not ask any question.\n"
    yield "Mave: I'll see you tommorow.\n"
    yield "Prologue: Chapter 1 completed\n"